theme = "dracula"

[editor]
line-number = "relative"

[editor.cursor-shape]
insert = 'bar'
normal = 'block'
select = 'underline'

[editor.whitespace]
render = 'all'
characters = { newline = '¬' }

[editor.file-picker]
hidden = false