[[language]]
name = "typescript"
auto-format = true
language-server = { command = "typescript-language-server", args = ["--stdio"] }

[[language]]
name = "tsx"
auto-format = true
language-server = { command = "typescript-language-server", args = ["--stdio"] }

[[language]]
name = "go"
indent = { tab-width = 2, unit = " " }
auto-format = true

[[language]]
name = "erb"
indent = { tab-width = 2, unit = "\t" }
file-types = ["cfm"]

[[language]]
name = "java"
indent = { tab-width = 2, unit = "\t" }
file-types = ["cfc"]

[[language]]
name = "python"
scope = "source.python"
indent = { tab-width = 4, unit = " " }
formatter = { command = "black", args = ["-", "--line-length=88",] }
auto-format = true
